config/routes.rb
FirstApp::Application.routes.draw do

  devise_for :users
  # quando acessar a url principal vai para o controler welcome e chama a index
  root 'welcome#index'

  # pega o nome da url "black" e atribui a uma difinição no controller welcome
  get 'black', to: 'welcome#black'
  
  get '/about', to: 'welcome#about', as: :about

  # cria uma rota de biils dentro de usuarios
  resources :users do
  	resources :bills
  end
end

app/models/bill.rb
class Bill < ActiveRecord::Base
	validates :name, presence: true, allow_blank: false
	validates :user_id, presence: true
	validates :date, presence: true
	validates :value, presence: true

	belongs_to :user

	# pedaço de query que é adicionado sempre no final do select
	# neste caso adiiciona um orderby
	default_scope {order('bills.date DESC')}
	scope :recents, -> {order('bills.date DESC').limit(5)}
	scope :yesterday, -> {where('bills.date > ?', 1.day.ago)}

	scope :before_yesterday, -> {
		where('bills.date > ?', 2.days.ago).
		where.not('bills.date > ?', 1.days.ago)
	}

	scope :days_ago, ->(x) {
		where('biils.date > ?' , x.days.ago)
	}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	# Constants
	FEMALE = 1;
	MALE = 2;

	# Validations
	validates :email, presence: true, allow_blank: false
	validates :name, presence: true, allow_blank: false
	validates :gender, presence: true, if: :adulthood
	validates_uniqueness_of :email

	has_many :bills, dependent: :destroy

	# Associations

	# Scopes

	# Public methods
	def adulthood
		self.age.present? and self.age > 18
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u|
  		u.permit(:name, :email, :password, :password_confirmation)
  	}
  	devise_parameter_sanitizer.for(:edit){ |u| 
  		u.permit(:name, :email, :password, :password_confirmation)
  	}
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	def create
		@bill = Bill.new bill_params
		@bill.user_id = params[:user_id]
		@bill.save
	end

	def destroy
		@bill = Bill.find(params[:id])
		@bill.destroy
	end

	def edit
		@bill = Bill.find(params[:id])
	end

	def update
		@bill = Bill.find(params[:id])
		@bill.update bill_params
	end

	private

	def bill_params
		params.require(:bill).permit(:name, :description, :value, :date)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			redirect_to users_path
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update user_params
			render :show
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])

		if @user.destroy
			flash[:notice] = "Usuário Removido com sucesso"
		else
			flash[:notice] = "Falha na remoção de usuário"
		end
		
		#@user.destroy
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :age, :gender)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	before_filter :authenticate_user!, except: [:index, :about]
		
	# metodo contrutor da página inicial
	def index
		@name = "Fábio Calheiros"
	end

	# metodo black aponta para um novo layout
	# o layout deve estar dentro da pasta welcome para que funcione
	def black
		@text = "Esta é uma página com novo layout"
		render layout: 'application_black'
	end

	def about
		@address = "Rua Maranhão, 1283"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message

		return nil if flash[:notice].nil?

		html = <<-HTML
		<div class="alert alert-info">
			#{ flash[:notice] }
		</div>
		HTML
		flash[:notice] = nil
		html.html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def gender_name(user)
		if user.gender == User::MALE
			"Masculino"
		elsif user.gender == User::FEMALE
			"Feminino"
		else
			"Não Definido"
		end
	end
end

app/views/bills/_bill.html.erb
<%= div_for bill, class: 'alert alert-info' do %>

	<b><%= bill.name %></b> - <%= bill.description %>
	<br>
	<%= l(bill.date, format: :long) %>
	<br>
	<%= number_to_currency bill.value %>

	<%= link_to "<i class='bt_edicao glyphicon glyphicon-pencil'></i>".html_safe,
				edit_user_bill_path(bill.user, bill),
				remote: true,
				class: 'pull-right' %>

	<%= link_to "<i class='bt_edicao glyphicon glyphicon-trash'></i>".html_safe,
				[bill.user, bill],
				method: :delete,
				remote: true,
				class: 'pull-right' %>
<% end %>

app/views/bills/_form.html.erb
<h5>Nova Conta</h5>

<!-- remote: true'= requisição ajax -->

<%= render partial: 'shared/error_messages', locals: {resource:bill} %>

<%= form_for( [bill.user, bill], remote: true) do |f| %>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Nome da Conta</span>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<br>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Descrição da conta</span>
		<%= f.text_area :description, class: 'form-control' %>
	</div>
	<br>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Valor</span>
		<%= f.text_field :value, class: 'form-control' %>
	</div>
	<br>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Data da Conta</span>
		<%= f.date_field :date, class: 'form-control' %>
	</div>
	<br>
		
	<br>
	<%= f.submit "Salvar conta", class: "btn btn-success" %>
<% end %>

app/views/bills/_index.html.erb
<% if bills.any? %>
	<% bills.each do |bill| %>
		<%= render bill %>
	<% end %>
<% else %>
	<div class="alert alert-warning"> 
		Não há contas registradas!
	</div>
<% end %>

app/views/bills/create.js.erb
<% if @bill.persisted? %>
	<% form = render partial: 'bills/form', locals: {bill: Bill.new(user: @bill.user)} %>
	$("#new_bill").html("<%= j(form) %>");

	<% index = render partial: 'bills/index', locals: {bills: @bill.user.bills} %>
	$("#bills").html("<%= j(index) %>");

<% else %>
	<% form = render partial: 'bills/form', locals: {bill: @bill} %>
	$("#bills").html("<%= j(form) %>");
<% end %>

app/views/bills/destroy.js.erb
<% if @bill.destroyed? %>
	$("#bill_<%= @bill.id %>").remove();
<% end %>

app/views/bills/edit.js.erb
<% form = render partial: 'bills/form', locals: {bill: @bill}  %>
$("#new_bill").html("<%= j form %>")

$("html, body").animate({
	scrollTop: $("#new_bill").offset().top - 70
});

app/views/bills/update.js.erb
<% if @bill.valid? %>
	<% form = render partial: 'bills/form', locals: {bill: Bill.new(user: @bill.user)} %>
	$("#new_bill").html("<%= j(form) %>");

	$("#bill_<%= @bill.id %>").replaceWith("<%= j(render @bill) %>");	

	$("html, body").animate({
		scrollTop: $("#bill_<%= @bill.id %>").offset().top - 70
	});

<% else %>
	<% form = render partial: 'bills/form', locals: {bill: @bill} %>
	$("#new_bill").html("<%= j(form) %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<%= render partial: 'shared/navbar' %>

    <div class="container">

      <div class="row">

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      	<div class="col-md-9">
      		<%= yield %>
      	</div>

      	<div class="col-md-3">
      		<!-- testa se o conteudo sidebar que esta dentro do template index existe -->
      		<% if content_for? :sidebar %>
      		<!-- se a sidebar existe traz a sidebar que esta dentro do index -->
      			<%= yield :sidebar %>
      		<% else %>
      		<!-- se a sidebar não existe traz o include padrao -->
      			<%= render partial: 'shared/sidebar' %>
			<% end %>      		
      	</div>

      </div>

    </div><!--/.container-->




</body>
</html>

app/views/layouts/application_black.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #e4e4e4">

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
	<div class="alert alert-danger">
		<h2>
			<%= pluralize(resource.errors.count, "Erro", "Erros") %>
		</h2>
		<ul>
			<% resource.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to "Projeto Framework", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:action]== 'index' ? 'active' : '' %>">
               <%= link_to "Página Inicial", root_path %>
            </li>
            <li class="<%= params[:action]== 'about' ? 'active' : '' %>">
              <%= link_to "Sobre", about_path %>
            </li>
            <li><a href="#contact">Contact</a></li>

            <% if user_signed_in? %>
            <li>  
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
             <li>  
              <%= link_to "Editar Conta", edit_user_registration_path(current_user) %>
            </li>
            <% else %>
            <li>
              <%= link_to "login", new_user_session_path, class: 'btn' %>
            <% end %>
            </li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

app/views/shared/_sidebar.html.erb
<div class="list-group">
	            <a href="#" class="list-group-item active">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
	            <a href="#" class="list-group-item">Link</a>
          	</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
	
	<%= render partial: 'shared/error_messages', locals: {resource:user} %>

	<div class="input-group col-md-6">
		<span class="input-group-addon">Nome</span>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<br>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Email</span>
		<%= f.email_field :email, class: 'form-control' %>
	</div>
	<br>
	<div class="input-group col-md-6">
		<span class="input-group-addon">Idade</span>
		<%= f.number_field :age, class: 'form-control' %>
	</div>
	<br>
		
	<div class="input-group col-md-6">
		<% options = [ ["Feminino", User::FEMALE ], ["Masculino", User::MALE]] %>
		<%= f.select :gender, options, {include_blank: "-- Escolha um sexo --"}, class: 'form-control ' %>
	</div>
	
	<br>
	<%= f.submit "Salvar", class: "btn btn-success" %>

<% end %>

app/views/users/edit.html.erb
<h2>
	Editar Usuário
</h2>

<%= render partial: 'form', locals: {user: @user}  %>

app/views/users/index.html.erb
<%= flash_message %>

<% if @users.any? %>
	<% @users.each do |user| %>
	<div class="well">
		<i class="glyphicon glyphicon-user"></i>
		<%= "<b>#{user.name}</b>".html_safe %>
		&nbsp;&nbsp;
		<% view_icon = "<i class='glyphicon glyphicon-eye-open'></i>".html_safe %>
		<%= link_to view_icon, user, class: "btn btn-default btn-xs" %>
		
		<% view_icon = "<i class='glyphicon glyphicon-pencil'></i>".html_safe %>
		<%= link_to view_icon, edit_user_path(user), class: "btn btn-default btn-xs" %>

		<% view_icon = "<i class='glyphicon glyphicon-trash'></i>".html_safe %>
		<%= link_to view_icon, user, method: :delete, class: "btn btn-default btn-xs" %>
	</div>
	<% end %>
<% else %>
	<div class="alert">
		Não há usuários cadastrados
	</div>
<% end %>

<%= link_to "Novo Usuário", new_user_path, class: 'btn btn-success' %>

app/views/users/new.html.erb
<h4>Novo Usuário</h4>

<%= render partial: 'form', locals: {user: @user} %>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>

<p><b>Email:</b> <%= @user.email %></p>

<p><b>Quando Nasceu:</b> <%= time_ago_in_words @user.age.years.ago %></p>

<p><b>Sexo:</b> <%= gender_name @user %></p>

<p><b>Data de Criação:</b> <%= l(@user.created_at, format: :long) %></p>

<p><b>Última atualização feita em:</b> <%= time_ago_in_words @user.updated_at %></p>

<p><b>Tempo entre criação e edição:</b> <%= distance_of_time_in_words @user.updated_at, @user.created_at %></p>

<%= link_to t('back'), users_path, class: 'btn btn-default' %>
<%= link_to t('edit'), edit_user_path(@user), class: 'btn btn-primary' %>

<br><br>

<h4> Contas do usuário <b><%= @user.name %></b></h4>

<div id="new_bill">
	<%= render partial: 'bills/form', locals: {bill: Bill.new(user: @user)} %>
</div>

<hr>

<div id="bills">
	<!-- Renderiza o partial index dentro de bills e passa pra ele os bills -->
	<%= render partial: 'bills/index', locals: {bills: [@user.bills]} %>
</div>

app/views/welcome/about.html.erb
<h2><%= @address %></h2>

app/views/welcome/black.html.erb
<h1><%= @text %></h1>

app/views/welcome/index.html.erb
<h1 class="btn btn-success"><%= t('hello') %>, <%= @name %></h1>

<br><br>

<% label = "Listagem de Usuários" %>
<%= link_to label, users_path, class: 'btn btn-default' %>

<% if @name == "Fábio Calheiros" %>
	
	<%= content_for :sidebar do %>
		menu lateral
	<% end %>

<% end %>